name : Linters
on :
  push :
    branches :
      - main
    paths :
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'yarn.lock'
      - '.github/workflows/lint.yml'
  pull_request :
    paths :
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'yarn.lock'
      - '.github/workflows/lint.yml'


defaults :
  run :
    shell : 'bash'

jobs :
  eslint :
    runs-on : ubuntu-latest

    steps :
      - uses : actions/checkout@v5
      - uses : actions/setup-node@v5
        with :
          node-version : 24
          cache : 'yarn'

      # TODO: Install not all dependencies, but only those required for this workflow
      - name : Install dependencies
        run : yarn install --frozen-lockfile

      - run : yarn run lint
